version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: foodly_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: foodly_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Admin1.
      MYSQL_DATABASE: foodlyapp.ge
      MYSQL_USER: foodly
      MYSQL_PASSWORD: Admin1.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    name: foodly_network
